name: Cognito

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        required: true
        description: Environment

jobs:
  Deploy:
    runs-on: ubuntu-24.04

    environment: ${{ inputs.environment }}

    env:
      TF_IN_AUTOMATION: true
      TF_INPUT: false

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Get Credentials
        uses: catnekaise/cognito-idpool-auth@v1.0.2
        with:
          auth-flow: "enhanced"
          aws-region: "eu-west-1"
          aws-account-id: ${{ vars.AWS_ACCOUNT_ID }}
          cognito-identity-pool-id: "eu-west-1:68e8908a-f6be-4f14-af3a-7b627420a0d1"
          set-in-environment: true

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3
          terraform_wrapper: true

      - name: Terraform Init
        run: terraform init -lockfile=readonly -backend-config=./config/${{ inputs.environment }}/s3.tfbackend

      # - name: Terraform Plan
      #   run: terraform plan -compact-warnings

      - name: Terraform Apply
        run: terraform apply -auto-approve
